version: 2

updates:
  - package-ecosystem: cargo
    directories:
      - /
      - /fuzz
    schedule:
      interval: daily
      time: "05:23"
      timezone: America/Mexico_City
    open-pull-requests-limit: 3
    rebase-strategy: auto
    groups:
      rust-security:
        applies-to: security-updates
        patterns:
          - "*"
      rust-compatible:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:43"
      timezone: America/Mexico_City
    open-pull-requests-limit: 1
    rebase-strategy: auto
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directories:
      - /installer/package
      - /installer/bundle
    schedule:
      interval: daily
      time: "06:03"
      timezone: America/Mexico_City
    open-pull-requests-limit: 1
    rebase-strategy: auto
    groups:
      wix:
        patterns:
          - "*"
